namespace tables_project_api.Dtos
{
    public class AutoGeneratedJobDataDto
    {
        public string Position { get; set; }
        public string Company { get; set; }
        public string Location { get; set; }
        public DateTime DateApplied { get; set; }
    }
}
