using AutoMapper;
using System.Net;
using System.Text;
using System.Text.Json;
using tables_project_api.Dtos;
using tables_project_api.Interfaces;
using tables_project_api.Models;

namespace tables_project_api.Services
{
    public class TableService : ITableService
    {
        private readonly ITableRepository _tableRepository;
        private readonly IMapper _mapper;

        public TableService(ITableRepository tableRepository, IMapper mapper)
        {
            _tableRepository = tableRepository;
            _mapper = mapper;
        }

        public TableReturnDto GetTableByUserId(int userId)
        {
            Table? table = _tableRepository.getTableByUserId(userId);
            if (table == null) throw new Exception(message: "invalid userId");

            List<Column> columns = table.Columns.ToList();

            Column? bottomRowColumn = columns.Find(column => column.ColumnIsBottomRowValue != null);

            var rows = MapRowsToTableRowDtos(table.Rows, columns);

            return new TableReturnDto()
            {
                Columns = _mapper.Map<ICollection<ColumnReturnDto>>(table.Columns),
                TopRows = rows.ToList().Where((row) => !CheckIsBottomRow(row, bottomRowColumn)),
                BottomRows = rows.ToList().Where((row) => CheckIsBottomRow(row, bottomRowColumn))
                //BottomRowColumnId = bottomRowColumn != null ? bottomRowColumn.Id : null,
                //BottomRowValue = bottomRowColumn != null ? bottomRowColumn.ColumnIsBottomRowValue!.Value : null,
            };
        }

        private bool CheckIsBottomRow(TableRowReturnDto row, Column? bottomRowColumn)
        {
            return row.Datacells.ToList().Find((datacell) => datacell.ColumnId == bottomRowColumn?.Id)?.Value ==
            bottomRowColumn?.ColumnIsBottomRowValue?.Value;
        }

        private ICollection<TableRowReturnDto> MapRowsToTableRowDtos(ICollection<Row> rows, List<Column> columns)
        {

            var outputRows = new List<TableRowReturnDto>();
            foreach (var row in rows)
            {
                var outputRow = new TableRowReturnDto()
                {
                    Id = row.Id,
                    Color = GetRowColor(row, columns),
                    Datacells = GetRowDatacells(row, columns)
                };
                outputRows.Add(outputRow);
            }
            return outputRows;
        }

        private string GetRowColor(Row row, List<Column> columns)
        {
            Column? responsibleColumn = columns.Find(columns => columns.ColumnColorsValues != null);
            if (responsibleColumn == null)
            {
                return "none";
            }

            Datacell? responsibleDatacell = row.Datacells.ToList().Find(datacell => datacell.Column.Id == responsibleColumn.Id);
            if (responsibleDatacell == null)
            {
                return "none";
            }

            foreach (var colorValue in responsibleColumn.ColumnColorsValues!.ColorsValues)
            {
                if (responsibleDatacell.Value.Equals(colorValue.Value))
                {
                    return colorValue.Color;
                }
            }

            return "none";
        }

        private ICollection<TableDatacellReturnDto> GetRowDatacells(Row row, List<Column> columns)
        {
            var outputDatacells = new List<TableDatacellReturnDto>();
            foreach (var datacell in row.Datacells)
            {
                Column? coorespondingColumn = columns.Find(column => datacell.Column.Id == column.Id);
                if (coorespondingColumn == null) throw new Exception("No corresponding column for row found");

                outputDatacells.Add(new TableDatacellReturnDto()
                {
                    Id = datacell.Id,
                    Value = datacell.Value,
                    ColumnId = datacell.Column.Id,
                    IsLastColumn = datacell.Column.Id == columns.Last().Id,
                    Dropdown = coorespondingColumn.Dropdown != null ? new DropdownDto() { Options = _mapper.Map<ICollection<DropdownOptionReturnDto>>(coorespondingColumn.Dropdown.Options) } : null,
                    Datepicker = coorespondingColumn.Datepicker != null ? new DatepickerDto() { } : null,
                });
            }

            return outputDatacells;
        }

        public void UpdateDatacellValueById(int id, string newValue)
        {
            _tableRepository.UpdateDatacellValueById(id, newValue);
        }

        public AutoGeneratedJobDataDto AutoGenerateJobData(InputURLDto inputURLDto)
        {
            ScrapedJobDataDto scrapedData = getScrapedJobData(inputURLDto);
            DateTime currentDate = DateTime.UtcNow.Date;
            return new AutoGeneratedJobDataDto()
            { Company = scrapedData.Company, DateApplied = currentDate, Location = scrapedData.Location, Position = scrapedData.Position };
        }

        private ScrapedJobDataDto getScrapedJobData(InputURLDto inputURLDto)
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("http://127.0.0.1:8000/");

            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };

            var json = JsonSerializer.Serialize(inputURLDto);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync("extractData", content).Result;
            if (response.IsSuccessStatusCode)
            {
                Stream? responseContent = response.Content.ReadAsStreamAsync().Result;
                ScrapedJobDataDto? postResponse = JsonSerializer.Deserialize<ScrapedJobDataDto>(responseContent, options);
                if (postResponse == null) throw new Exception("Server error");
                return postResponse;
            }
            else
            {
                if (response.StatusCode == HttpStatusCode.BadRequest)
                {
                    throw new Exception("Invalid URL");
                }
                else
                {
                    throw new Exception("Server error");
                }
            }
        }
    }
}
