version: "3.9"
services:
  reverse-proxy:
    build: 
      context: ./Nginx
    ports:
      - "80:80"
      - "443:443"
  tables-project-api:
    image: tables-project-api
    container_name: tables-project-api-application
    build: 
      context: ./tables-project-api
    depends_on:
      - reverse-proxy
    expose:
      - "433"