services:
  tables-project-api:
    image: tables-project-api
    build:
      context: ./tables-project-api
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-services
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy_data:/data
      - /data/caddy_config:/config
  # frontend:
  #   depends_on:
  #     - tables-project-api
  #     # - caddy
  #   image: tables-project-api-frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "80:3000"
