# version: "3.9"
# services:
#   web_api:
#     image: web_api
#     container_name: web_api_application
#     ports:
#       - "5000:80"
#   sql:
#     image: "mcr.microsoft.com/mssql/server:2022-latest"
#     container_name: sql_server_tablesio
#     ports: # not actually needed, because the two services are on the same network
#       - "1433:1433" 
#     environment:
#       - ACCEPT_EULA=y
#       - SA_PASSWORD=A&VeryComplex123Password

dotnet dev-certs https -ep $env:USERPROFILE\.aspnet\https\tables-project-api.pfx -p root
dotnet dev-certs https --trust

docker run --rm -it -p 8001:8001 -e ASPNETCORE_HTTPS_PORTS=8001 -e ASPNETCORE_ENVIRONMENT=Development -v $env:APPDATA\microsoft\UserSecrets\:/root/.microsoft/usersecrets -v $env:USERPROFILE\.aspnet\https:/root/.aspnet/https/ aspnetapp