version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  tables-project-api:
    image: tables-project-api
    container_name: tables-project-api
    build: 
      context: ./tables-project-api
    networks:
      - internal
  # ghost:
  #   image: ghost:4-alpine
  #   restart: unless-stopped
  #   environment:
  #           - url=https://tables-project-api.tablesio.com 
  #   volumes:
  #           - /data/myghostapp:/var/lib/ghost/content
  #   networks:
  #           - internal
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-services
    restart: unless-stopped
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - /data/caddy_data:/data
      - /data/caddy_config:/config
    networks:
      - web
      - internal

volumes:
  caddy_data:
  caddy_config: