using tables_project_api.Dtos;

namespace tables_project_api.Interfaces
{
    public interface ITableService
    {
        TableReturnDto GetTableByUserId(int userId);
        TableRowReturnDto UpdateDatacellValueById(int id, string newValue);
        AutoGeneratedJobDataDto AutoGenerateJobData(InputURLDto inputURLDto);
    }
}
