using tables_project_api.Dtos;

namespace tables_project_api.Interfaces
{
    public interface ITableService
    {
        //TableReturnDto getTableByUserId(int userId); // might need to get mapped to dto
        AutoGeneratedJobDataDto autoGenerateJobData(InputURLDto inputURLDto);
    }
}
