using tables_project_api.Dtos;
using tables_project_api.Models;

namespace tables_project_api.Interfaces
{
    public interface ITableService
    {
        TableReturnDto GetTableByUserId(int userId);
        TableRowReturnDto UpdateDatacellValueById(int id, string newValue);
        AutoGeneratedJobDataDto AutoGenerateJobData(InputURLDto inputURLDto);
        TableRowReturnDto AddRow(InputRowDto inputRowDto);
        void RemoveRowById(int id);
    }
}
