using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using tables_project_api.Dtos;
using tables_project_api.Interfaces;

namespace tables_project_api.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TableController : Controller
    {
        private readonly ITableService _tableService;

        public TableController(ITableService tableService)
        {
            this._tableService = tableService;
        }
        

        [HttpGet("{userId}")]
        [ProducesResponseType(200, Type = typeof(TableReturnDto))]
        public IActionResult GetTableByUserId(int userId)
        {
            //try
            //{
            return Ok(_tableService.GetTableByUserId(userId));
            //}
            //catch
            //{
            //    return StatusCode(StatusCodes.Status500InternalServerError);
            //};
        }

        [HttpPost("autoGenerateJobData")]
        [ProducesResponseType(201, Type = typeof(TableRowReturnDto))]
        public IActionResult AutoGenerateJobData([FromBody][Required] InputURLDto inputURLDto)
        {
            AutoGeneratedJobDataDto jobData = _tableService.AutoGenerateJobData(inputURLDto);
            return StatusCode(StatusCodes.Status201Created, _tableService.AddRow(new InputRowDto()
            {
                TableId = inputURLDto.TableId,
                DatacellValues = new List<string>() {
                    jobData.Position,
                    jobData.Company,
                    jobData.Location,
                    jobData.DateApplied.ToString(),
                    "No response"
                }

            }
            ));
        }

        [HttpPatch("updateDatacellValueById/{datacellId}")]
        [ProducesResponseType(200, Type = typeof(TableRowReturnDto))]
        public IActionResult UpdateDatacellValueById(int datacellId, [FromBody][Required] InputDatacellValueDto inputDatacellValueDto)
        {
            return Ok(_tableService.UpdateDatacellValueById(datacellId, inputDatacellValueDto.Value));
        }

        // not used yet
        [HttpPost("addRow")]
        [ProducesResponseType(201, Type = typeof(TableRowReturnDto))]
        public IActionResult AddRow([FromBody][Required] InputRowDto inputRowDto)
        {
            return StatusCode(StatusCodes.Status201Created, _tableService.AddRow(inputRowDto));
        }

        [HttpDelete("removeRowById/{id}")]
        [ProducesResponseType(200)]
        public IActionResult RemoveRowById(int id)
        {
            _tableService.RemoveRowById(id);
            return Ok();
        }
    }
}
